version: '3.9'

services:
  dynamo:
    container_name: dynamodb
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: ["-jar", "DynamoDBLocal.jar", "-optimizeDbBeforeStartup", "-sharedDb", "-dbPath", "."]

volumes:
  dynamodata: